name: "branch deploy demo"

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read
  statuses: read

jobs:
  triggered-deploy:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.tmp_stage_name.outputs.branch }}
    steps:
      - name: Extract commit SHA
        run: echo "sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT
        id: extract_sha

      - name: Build temporary stage name with hyphen and 8-char SHA
        run: echo "branch=tst-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
        id: tmp_stage_name

      - uses: github/branch-deploy@v10.3.1
        id: branch-deploy
        with:
          trigger: ".deploy"
          environment: ${{ steps.tmp_stage_name.outputs.branch }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.branch-deploy.outputs.sha }}

      - name: Fake noop deploy on environment
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop == 'true' }}
        run: echo "I am doing a fake noop deploy on environment ${{ steps.branch-deploy.outputs.environment }}"

      - name: Fake regular deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' }}
        run: echo "Regular deploys are not allowed for this repository. Please use noops."

  write-comment:
    needs: triggered-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Write a comment on the PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deployed to environment ${{ needs.triggered-deploy.outputs.environment }}'
            })
